[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts', '@chainlink/contracts@1.0.0=lib/chainlink/contracts']

# [fuzz]
# seed = "0x1"

# [invariant]
# runs = 1000
# depth = 32
# fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
